### PR TITLE
fix: support toml values with equal sign

### LINKED ISSUE #179: Using other markdown or html in titles
Hi, awesome tool!

Question, is it possible to somehow use markdown or html formating within titles ?

EG

admonish tip title="Some New Structure `my_structure`"

Any way to achieve this currently ?

Greetings,

### PR DESCRIPTION
**Pull request by tommilligan**
Closes #179 

The v2 config format is not suitable for parsing complex toml values, specifically containing `=` values. This is due to the pre-parsing wrangling to marshal key-value pairs into a valid TOML format using `=` as a marker for TOML keys, when in fact it can appear in values too.

To fix this, introduce the new v3 config format which uses the [TOML Inline Table](https://toml.io/en/v1.0.0#inline-table) syntax to support this natively.

This PR adds the config back-compatibly, falling back to v2 (and v1) if parsing with the new format fails. It also updates all docs/examples to use the new comma separated format where appropriate.

### CODE REVIEW

File: src/config/v2.rs [hunk 1]
```diff
@@ -60,19 +56,11 @@ pub(crate) fn from_config_string(config_string: &str) -> Result<InstanceConfig,
...
+                return Err(format_invalid_directive(directive, original_error));
             }
 
-            let mut config: UserInput = match toml::from_str(config_toml) {
-                Ok(config) => config,
-                Err(error) => {
-                    return Err(format!("TOML parsing error: {error}"));
-                }
-            };
+            let mut config = user_input_from_config_toml(dbg!(config_toml))?;
```
Comment (s00500) [inline src/config/v2.rs:63]: Hey @tommilligan, seems like this line now causes quite some prints during the build that are not really relevant. Very minor issue, but maybe that was not intended ?

Looks like this: 
`.cargo/registry/src/index.crates.io-6f17d22bba15001f/mdbook-admonish-1.17.0/src/config/v2.rs:63:58] config_toml = "collapsible=true \ntitle=\"Display value (without control)\""`

Comment (tommilligan) [reply src/config/v2.rs:63]: Thanks, yes this was indeed unintentional. Opened #186 to resolve
